name: Main CI

on:
  pull_request:
  workflow_dispatch:
  
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
          
      - name: install-dependencies
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install nodejs -y
          sudo apt install npm -y
          
          pushd server || exit 1
          npm install
          popd || exit 1
        
      - name: build
        run: |
          pushd server || exit 1
          rm -rf dist
          cp .env.example .env.test
          env=test npm run build
          if [ $? -ne 0 ]; then
            echo "Build failed!"
            exit 1
          fi
          popd || exit 1
     
      - name: test
        run: |
          pushd server || exit 1
          rm -rf dist
          env=test npm run test
          if [ $? -ne 0 ]; then
            echo "Some tests failed!"
            exit 1
          fi
          popd || exit 1
